# Generated by Django 3.2.9 on 2021-11-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='type',
            field=models.CharField(choices=[('Funding', 'Funding'), ('Repayment', 'Repayment')], max_length=50),
        ),
    ]
